@host = http://localhost:5001

GET {{host}}/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOTg2NDM4NSIsIm5hbWUiOiLQndC10LHRi9GC0L7QsiDQlNCw0L3QuNC40LsiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIzOTg2NDM4NSIsImV4cCI6MTY2NzYzNzc4OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxIn0.fmuUId7XP_E-t6qdXb9YoImtq3zIdjPNBKMJyhrG4m0